"""timezone-update

Revision ID: 16bfd0c31f8d
Revises: acd891fba842
Create Date: 2023-11-04 05:55:42.686925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "16bfd0c31f8d"
down_revision = "acd891fba842"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
