"""init

Revision ID: 58f8f97b373d
Revises: 57aa2fa4e523
Create Date: 2023-05-01 18:25:53.176603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f8f97b373d'
down_revision = '57aa2fa4e523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
