"""add-count

Revision ID: c3efafd39489
Revises: 16bfd0c31f8d
Create Date: 2023-12-04 17:31:00.782108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c3efafd39489"
down_revision = "16bfd0c31f8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "count",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_count_id"), "count", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_count_id"), table_name="count")
    op.drop_table("count")
    # ### end Alembic commands ###
