"""init

Revision ID: c844a2ac7f42
Revises: 
Create Date: 2024-03-11 07:25:32.668655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c844a2ac7f42'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_account_user_id'), 'account', ['user_id'], unique=False)
    op.create_index(op.f('ix_account_username'), 'account', ['username'], unique=True)
    op.create_index('username_case_sensitive_index', 'account', [sa.text('upper(username)')], unique=True)
    op.create_table('blogs',
    sa.Column('blog_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('preview', sa.String(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('image', sa.String(), server_default='default.png', nullable=False),
    sa.Column('date_posted', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_edited_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['account.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blog_id'),
    sa.UniqueConstraint('title')
    )
    op.create_index(op.f('ix_blogs_blog_id'), 'blogs', ['blog_id'], unique=False)
    op.create_index(op.f('ix_blogs_date_posted'), 'blogs', ['date_posted'], unique=False)
    op.create_index(op.f('ix_blogs_last_edited_date'), 'blogs', ['last_edited_date'], unique=False)
    op.create_index(op.f('ix_blogs_slug'), 'blogs', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blogs_slug'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_last_edited_date'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_date_posted'), table_name='blogs')
    op.drop_index(op.f('ix_blogs_blog_id'), table_name='blogs')
    op.drop_table('blogs')
    op.drop_index('username_case_sensitive_index', table_name='account')
    op.drop_index(op.f('ix_account_username'), table_name='account')
    op.drop_index(op.f('ix_account_user_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
