"""update-slug

Revision ID: ccbbf534dce5
Revises: 8a38f33dc799
Create Date: 2024-03-11 05:50:37.208549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, select, update
from app.models.core import Blog

# revision identifiers, used by Alembic.
revision = 'ccbbf534dce5'
down_revision = '8a38f33dc799'
branch_labels = None
depends_on = None


def upgrade():
    blogs_table = table('blogs',
                        sa.Column('blog_id', sa.Integer, primary_key=True),
                        sa.Column('title', sa.String),
                        sa.Column('slug', sa.String))


    connection = op.get_bind()
    blogs = connection.execute(select(blogs_table)).fetchall()
    for blog in blogs:
        slug = Blog.generate_slug(blog.title)
        update_stmt = update(blogs_table).where(blogs_table.c.blog_id == blog.blog_id).values(slug=slug)
        connection.execute(update_stmt)

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_count_id', table_name='count')
    op.drop_table('count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('count',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='count_pkey')
    )
    op.create_index('ix_count_id', 'count', ['id'], unique=False)
    # ### end Alembic commands ###
