name: Build Docker Images

on:
  push:
    branches:
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vichannnnn/hima-blog-app

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Path filter
        id: path-filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            frontend:
              - 'frontend/**'
            backend:
              - 'backend/**'

      - name: Set up Docker Buildx
        if: steps.path-filter.outputs.frontend == 'true' || steps.path-filter.outputs.backend == 'true'
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        if: steps.path-filter.outputs.frontend == 'true' || steps.path-filter.outputs.backend == 'true'
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        if: steps.path-filter.outputs.frontend == 'true' || steps.path-filter.outputs.backend == 'true'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CICD_TOKEN }}

      - name: Build and push Backend Docker image
        if: steps.path-filter.outputs.backend == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/hima-blog-backend:latest

      - name: Build and push Frontend Docker image
        if: steps.path-filter.outputs.frontend == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ./frontend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/hima-blog-frontend:latest
