name: Deploy

on:
  workflow_run:
    workflows: ["Frontend build", "Backend build"]
    branches: [master]
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vichannnnn/hima-blog-app

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: executing remote ssh commands using private key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MASTER_REMOTE_HOST }}
          username: ${{ secrets.MASTER_REMOTE_USER }}
          key: ${{ secrets.MASTER_SSH_PRIVATE_KEY }}
          script: |
              cd hima-blog-app
              docker compose pull
              docker compose up -d
              make migrate
              rm -r ../api-gateway/hima-blog-app
              docker cp hima-blog-frontend:/usr/share/caddy/hima-blog-app ../api-gateway/hima-blog-app/
              docker compose stop hima-blog-frontend
              docker restart api-gateway
